# arena.py — the robot's environment, defined once. Pure Python, no ROS.
#
# The same ARENA drives both views of the world:
#   * Gazebo  -> to_sdf() renders worlds/arena.sdf (regenerate with
#                `python3 -m yoruba_robot.arena > worlds/arena.sdf`)
#   * RViz    -> environment_publisher turns ARENA into a MarkerArray
# A gate test fails if the committed arena.sdf drifts from to_sdf(), so the
# physics world and the RViz picture can never disagree.
#
# Frame: odom. The robot starts at (0, 0) facing +x. Units: metres.
# Edit ARENA to match your real room (measure it), regenerate, rebuild.
from __future__ import annotations

ARENA = {
    "size_x": 3.0,              # inner floor length along x
    "size_y": 3.0,              # inner floor width along y
    "wall_height": 0.25,
    "wall_thickness": 0.05,
    "start_clear_radius": 0.35,  # nothing may sit this close to the start pose
    "obstacles": [
        # name, shape, centre (x, y), size: box=(sx, sy, sz) cylinder=(radius, height)
        {"name": "crate", "shape": "box", "xy": (1.0, 0.7), "size": (0.30, 0.30, 0.20),
         "color": (0.80, 0.55, 0.25)},
        {"name": "bin", "shape": "cylinder", "xy": (-0.8, -0.7), "size": (0.12, 0.25),
         "color": (0.25, 0.65, 0.35)},
        {"name": "block", "shape": "box", "xy": (0.9, -0.9), "size": (0.40, 0.15, 0.12),
         "color": (0.75, 0.30, 0.30)},
    ],
    "floor_color": (0.78, 0.78, 0.74),
    "wall_color": (0.55, 0.57, 0.62),
}


def walls(a: dict = ARENA) -> list[dict]:
    """Four wall boxes enclosing the floor. Each: name, centre (x, y, z), size."""
    hx, hy, t, h = a["size_x"] / 2, a["size_y"] / 2, a["wall_thickness"], a["wall_height"]
    return [
        {"name": "wall_north", "xyz": (0.0, hy + t / 2, h / 2), "size": (a["size_x"] + 2 * t, t, h)},
        {"name": "wall_south", "xyz": (0.0, -hy - t / 2, h / 2), "size": (a["size_x"] + 2 * t, t, h)},
        {"name": "wall_east", "xyz": (hx + t / 2, 0.0, h / 2), "size": (t, a["size_y"], h)},
        {"name": "wall_west", "xyz": (-hx - t / 2, 0.0, h / 2), "size": (t, a["size_y"], h)},
    ]


def obstacle_extent(o: dict) -> tuple[float, float]:
    """Half-extents (x, y) of an obstacle's footprint."""
    if o["shape"] == "box":
        return o["size"][0] / 2, o["size"][1] / 2
    return o["size"][0], o["size"][0]


def obstacle_height(o: dict) -> float:
    return o["size"][2] if o["shape"] == "box" else o["size"][1]


def _f(v: float) -> str:
    return f"{v:.4f}".rstrip("0").rstrip(".") if v != 0 else "0"


def _v(*vals: float) -> str:
    return " ".join(_f(v) for v in vals)


def _material(rgb) -> str:
    r, g, b = rgb
    return (f"<material><ambient>{_v(r, g, b, 1)}</ambient>"
            f"<diffuse>{_v(r, g, b, 1)}</diffuse>"
            f"<specular>0.1 0.1 0.1 1</specular></material>")


def _static_box(name, xyz, size, rgb) -> str:
    geo = f"<geometry><box><size>{_v(*size)}</size></box></geometry>"
    return (f"    <model name=\"{name}\">\n"
            f"      <static>true</static>\n"
            f"      <pose>{_v(*xyz, 0, 0, 0)}</pose>\n"
            f"      <link name=\"link\">\n"
            f"        <collision name=\"col\">{geo}</collision>\n"
            f"        <visual name=\"vis\">{geo}{_material(rgb)}</visual>\n"
            f"      </link>\n"
            f"    </model>\n")


def _static_cylinder(name, xyz, radius, height, rgb) -> str:
    geo = (f"<geometry><cylinder><radius>{_f(radius)}</radius>"
           f"<length>{_f(height)}</length></cylinder></geometry>")
    return (f"    <model name=\"{name}\">\n"
            f"      <static>true</static>\n"
            f"      <pose>{_v(*xyz, 0, 0, 0)}</pose>\n"
            f"      <link name=\"link\">\n"
            f"        <collision name=\"col\">{geo}</collision>\n"
            f"        <visual name=\"vis\">{geo}{_material(rgb)}</visual>\n"
            f"      </link>\n"
            f"    </model>\n")


def to_sdf(a: dict = ARENA, world_name: str = "yoruba") -> str:
    """The Gazebo world for ARENA. Deterministic: same ARENA -> same bytes."""
    floor_x = a["size_x"] + 2 * a["wall_thickness"] + 1.0
    floor_y = a["size_y"] + 2 * a["wall_thickness"] + 1.0
    out = [
        "<?xml version=\"1.0\"?>\n",
        "<!-- GENERATED by yoruba_robot/arena.py. Do not edit by hand:\n",
        "     edit ARENA, then: python3 -m yoruba_robot.arena > worlds/arena.sdf -->\n",
        "<sdf version=\"1.9\">\n",
        f"  <world name=\"{world_name}\">\n",
        "    <physics name=\"step\" type=\"ignored\">\n",
        "      <max_step_size>0.002</max_step_size>\n",
        "      <real_time_factor>1.0</real_time_factor>\n",
        "    </physics>\n",
        "    <plugin filename=\"gz-sim-physics-system\" name=\"gz::sim::systems::Physics\"/>\n",
        "    <plugin filename=\"gz-sim-user-commands-system\" name=\"gz::sim::systems::UserCommands\"/>\n",
        "    <plugin filename=\"gz-sim-scene-broadcaster-system\" name=\"gz::sim::systems::SceneBroadcaster\"/>\n",
        "    <gravity>0 0 -9.81</gravity>\n",
        "    <scene><ambient>0.6 0.6 0.6 1</ambient><background>0.85 0.88 0.92 1</background>"
        "<shadows>true</shadows></scene>\n",
        "    <light name=\"sun\" type=\"directional\">\n",
        "      <cast_shadows>true</cast_shadows>\n",
        "      <pose>0 0 10 0 0 0</pose>\n",
        "      <diffuse>0.9 0.9 0.9 1</diffuse>\n",
        "      <specular>0.2 0.2 0.2 1</specular>\n",
        "      <direction>-0.4 0.3 -1</direction>\n",
        "    </light>\n",
        "    <model name=\"floor\">\n",
        "      <static>true</static>\n",
        "      <link name=\"link\">\n",
        "        <collision name=\"col\"><geometry><plane><normal>0 0 1</normal>"
        f"<size>{_v(floor_x, floor_y)}</size></plane></geometry>"
        "<surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface></collision>\n",
        "        <visual name=\"vis\"><geometry><plane><normal>0 0 1</normal>"
        f"<size>{_v(floor_x, floor_y)}</size></plane></geometry>{_material(a['floor_color'])}</visual>\n",
        "      </link>\n",
        "    </model>\n",
    ]
    for w in walls(a):
        out.append(_static_box(w["name"], w["xyz"], w["size"], a["wall_color"]))
    for o in a["obstacles"]:
        x, y = o["xy"]
        h = obstacle_height(o)
        if o["shape"] == "box":
            out.append(_static_box(o["name"], (x, y, h / 2), o["size"], o["color"]))
        else:
            out.append(_static_cylinder(o["name"], (x, y, h / 2), o["size"][0], h, o["color"]))
    out.append("  </world>\n</sdf>\n")
    return "".join(out)


def validate(a: dict = ARENA) -> list[str]:
    """Problems with an arena definition ([] = fine). Gate-tested."""
    errs = []
    hx, hy = a["size_x"] / 2, a["size_y"] / 2
    r0 = a["start_clear_radius"]
    names = set()
    for o in a["obstacles"]:
        if o["name"] in names:
            errs.append(f"duplicate obstacle name {o['name']}")
        names.add(o["name"])
        if o["shape"] not in ("box", "cylinder"):
            errs.append(f"{o['name']}: unknown shape {o['shape']}")
            continue
        ex, ey = obstacle_extent(o)
        x, y = o["xy"]
        if abs(x) + ex > hx or abs(y) + ey > hy:
            errs.append(f"{o['name']}: pokes through a wall")
        # distance from origin to the obstacle footprint (box: nearest point)
        dx, dy = max(abs(x) - ex, 0.0), max(abs(y) - ey, 0.0)
        if o["shape"] == "cylinder":
            d = max((x * x + y * y) ** 0.5 - ex, 0.0)
        else:
            d = (dx * dx + dy * dy) ** 0.5
        if d < r0:
            errs.append(f"{o['name']}: within {r0} m of the start pose")
    return errs


if __name__ == "__main__":
    import sys
    problems = validate()
    if problems:
        sys.exit("arena invalid: " + "; ".join(problems))
    sys.stdout.write(to_sdf())
